"""Added hashkey and name to Chat table

Revision ID: 7a789c0b44ab
Revises: 5553870311c5
Create Date: 2021-03-17 19:58:31.859355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a789c0b44ab'
down_revision = '5553870311c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('hash_key', sa.String(length=10), nullable=True))
    op.add_column('chat', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_chat_hash_key'), 'chat', ['hash_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_hash_key'), table_name='chat')
    op.drop_column('chat', 'username')
    op.drop_column('chat', 'hash_key')
    # ### end Alembic commands ###
